### ISSUE TITLE
Output formatting

### ISSUE THREAD

**Issue by LunarWatcher** [LunarWatcher/NN-chatbot#1]
don ' t you just hate reading messages like this ? Especially , since all the formatting is messed up by the bot and it ' s training . . .

Anyways, the "problem" (by design obviously) created [here](https://github.com/LunarWatcher/NN-chatbot/blob/master/datasetUtils.py#L127) is (supposed to be) cleaned up [here](https://github.com/LunarWatcher/NN-chatbot/blob/master/datasetUtils.py#L380), but it does so in a horrible, non-functioning manner. It works perfectly fine on the first few replaces, but after that the poorly constructed replace statements don't clean up properly.
These need to be fixed

**Comment by LunarWatcher** [comment]
something like:
 
    ( [',.?!-] ?)|( ?[',.?!-] )

*should* do. Untested

**Comment by TheOneWhoMade** [comment]
@LunarWatcher I can work on a regex. It's one of my skills I've picked up.

**Comment by TheOneWhoMade** [comment]
BTW you may want to do a series of filters.

**Comment by TheOneWhoMade** [comment]
check this out: https://regex101.com/r/UAIYbL/1.

All you need to do is make a few of these for each character you want to have no spaces.

**Comment by TheOneWhoMade** [comment]
Apostrophes:      https://regex101.com/r/UAIYbL/1
Question marks: https://regex101.com/r/UY3gve/1
Commas:             https://regex101.com/r/zEdPB7/1

I think you get the point.
@LunarWatcher

**Comment by TheOneWhoMade** [comment]
Do you get the point?

**Comment by LunarWatcher** [comment]
Final version:

    \s(?P<match>[?!.,])
    ( - - )
    (\s(?P<match2>['-])\s)
