### ISSUE TITLE
Setup script

### ISSUE THREAD

**Issue by LunarWatcher** [LunarWatcher/NN-chatbot#13]
A script that installs the dependencies, if not present. TheOneWhoMade's suggestion

**Comment by TheOneWhoMade** [comment]
```
import os
os.system("pip3.6 install numpy")
```
Thats a start

**Comment by TheOneWhoMade** [comment]
```
os.system("pip install beautifulsoup4")
```

**Comment by TheOneWhoMade** [comment]
Can I be assigned this?

**Comment by LunarWatcher** [comment]
You're not listed for some reason, so I can't. But it doesn't matter

**Comment by TheOneWhoMade** [comment]
Eh. Whatever. I can still work on it.

**Comment by LunarWatcher** [comment]
Tested. The system works

**Comment by TheOneWhoMade** [comment]
You used `main`, not system. Also: In about 10 minutes you will have a user of your repo.

**Comment by LunarWatcher** [comment]
Main is the one to use here

**Comment by TheOneWhoMade** [comment]
When I said ten minutes I meant 30. 0_0

**Comment by TheOneWhoMade** [comment]
With max optimizations on performance.

**Comment by TheOneWhoMade** [comment]
Crap. It was taking too long. Had to shut down.

**Comment by TheOneWhoMade** [comment]
Guess I'll try again next weekend. Raspberry Pi froze in the middle of the last step while using these instructions: https://hackaday.io/project/20448-elephant-ai/log/69535-guide-to-installing-tensorflow-on-raspberry-pi

**Comment by TheOneWhoMade** [comment]
Methinks I did something wrong.
