### ISSUE TITLE
Minification of bot.py

### ISSUE THREAD

**Issue by TheOneWhoMade** [LunarWatcher/NN-chatbot#15]
Please mark this as "enhancement".
Also please delay this until the project is finished.

Use any tricks and shortcuts you know to make `bot.py` smaller for quicker download size.
I know Python cannot be compressed exactly like JS (made into 1 line).
Stil it could be made a bit shorter.

**Comment by TheOneWhoMade** [comment]
This does need to be done right now, so if I could label it I would label it as "Priority: low"

**Comment by LunarWatcher** [comment]
I'm going to close this, because download size doesn't matter, it's still considerably less than a megabyte. And even then, the bot isn't a website script (where size does matter).

**Comment by TheOneWhoMade** [comment]
@LunarWatcher  the issue then is not size, but rather performance

**Comment by LunarWatcher** [comment]
Let me run some metrics

**Comment by TheOneWhoMade** [comment]
How are the metrics going so far?

**Comment by LunarWatcher** [comment]
The code edit you proposed is slower than the original code. I'm going to undo it now.

Proof:

```
from time import *

def ifOrTuple():
    combined = 0.0
    first = 0.0
    boolVal = False
    t = time()
    for i in range(10000000):
        "test" if boolVal else "testFalse"
    combined += time() - t
    print("Average: {}".format(combined))
    first = combined
    combined = 0.0
    t = time()
    for i in range(10000000):

        ("testFalse", "test")[boolVal]
    combined += time() - t
    print("Average: {}".format(combined))

if __name__ == "__main__":
    ifOrTuple()
```
Average: 0.39062047004699707
Average: 0.5312342643737793

The last one takes .2 seconds longer than the first one.

**Comment by TheOneWhoMade** [comment]
MK. Let me read this.

**Comment by TheOneWhoMade** [comment]
? Have you ever considered that that newline might impact it?

**Comment by TheOneWhoMade** [comment]
AND you are forgetting something. The usual condition in your bot is probably `True`. Try running it with true instead of false.

**Comment by TheOneWhoMade** [comment]
from time import *

def ifOrTuple():
    array = ("testFalse", "test")
    combined = 0.0
    first = 0.0
    boolVal = False
    t = time()
    for i in range(10000000):
        "test" if boolVal else "testFalse"
    combined += time() - t
    print("Average: {}".format(combined))
    first = combined
    combined = 0.0
    t = time()
    for i in range(10000000):
        array[boolVal||0]
    combined += time() - t
    print("Average: {}".format(combined))

if __name__ == "__main__":
    ifOrTuple()

**Comment by TheOneWhoMade** [comment]
Try that

**Comment by LunarWatcher** [comment]
No. Tuples will be created on the line in the code, not stored somewhere else. Sure, that could beat in benchmarking, but it'll still be as damn slow in production. When writing speed test code for stuff like this, **always** make sure it's **exactly** like it would be in real code

**Comment by TheOneWhoMade** [comment]
*Silently backs into a corner*

**Comment by TheOneWhoMade** [comment]
Are you saying that in **real** code it would actually be a dynamic value? Because at https://github.com/LunarWatcher/NN-chatbot/blob/master/Commands.py#L305 it is not a dynamic value.

**Comment by LunarWatcher** [comment]
No, I'm saying where touples are used, you don't store them like you did in your benchmarking

**Comment by TheOneWhoMade** [comment]
So they would not usualy be stored. Isn't that memory offensive? Making a new tuple every time...

**Comment by TheOneWhoMade** [comment]
If I can't help you, please look at http://www.algorithm.co.il/blogs/computer-science/10-python-optimization-tips-and-issues/

**Comment by LunarWatcher** [comment]
It is just created once. Storing them increases the chance of recreation. Why?

n.py:

    x = 1

m.py:

    for i in range(1000):
        import n.py # x is recreated 1000 times. 1 for each import

However:

    print("training" if training else "chatting") 

only creates the objects *when the line is called*. And the if-statement only creates one, the tuple creates two. No matter what. For these things, tuples are memory-inefficient

**Comment by TheOneWhoMade** [comment]
So they increase the complexity of the code?

**Comment by LunarWatcher** [comment]
As I have said multiple times already, **they use more memory**. Stuff that uses more memory usually allocates **more or bigger** objects. This:

    ("obj1", "obj2") == ["obj1", "obj2"]

where as:

    "training" if condition else "chatting"
     ==
    if condition: 
        obj = "training"
    else:
        obj = "chatting"

and *only creates one*. Complexity is completely irrelevant here

**Comment by TheOneWhoMade** [comment]
Yes I know the similarity between ternary and fullblown `if ... else ....`. But I get it now. **The system has to process all objects in a tuple, while in an if statement, it only procceses according to the condition**

**Comment by TheOneWhoMade** [comment]
You are so glad that I finally got the point? Wow.

**Comment by TheOneWhoMade** [comment]
```
#!/usr/bin/env python
ﵛ=ImportError
ࡅ=print
㮀=False
搓=object
try:
 import demiurgic
except ﵛ:
ࡅ("Warning: You're not demiurgic. Actually, I think that's normal.")
try:
 import mystificate
except ﵛ:
ࡅ("Warning: Dark voodoo may be unreliable.")
ﵩ=㮀
class רּ(搓):
 def __init__(self,*args,**kwargs):
  pass
 def 𐨱(self,dactyl):
  ﱲ=demiurgic.palpitation(dactyl)
  ꁁ=mystificate.dark_voodoo(ﱲ)
  return ꁁ
 def 𨠅(self,whatever):
  ࡅ(whatever)
if __name__=="__main__":
 ࡅ("Forming...")
 녂=רּ("epicaricacy","perseverate")
 녂.𨠅("Codswallop")
# Created by pyminifier.py (https://github.com/liftoff/pyminifier)
```
Source: https://github.com/liftoff/pyminifier#special-sauce 

Yeah that messes with me a lot. 
This is an example when you try to compress something so much you start using japanese characters. 😄

**Comment by TheOneWhoMade** [comment]
If you have ever played exploding kittens, you will get this joke:

```
Defuse card
     Play a snake game and learn the way
 of the snake. https://goo.gl/uRg6c7
```

**Comment by TheOneWhoMade** [comment]
Question. Do you think [this file change](https://github.com/LunarWatcher/NN-chatbot/compare/master...TheOneWhoMade:patch-1?expand=1) would be a decent change?

**Comment by LunarWatcher** [comment]
It's again a one-line commit. Technically it's two, but it's still the same. I don't even know why you spent time committing and undoing those same changes to multiple files. And I don't want to know. I'm going to lock this conversation
