### ISSUE TITLE
Make an index for sites

### ISSUE THREAD

**Issue by TheOneWhoMade** [LunarWatcher/NN-chatbot#18]
I noticed you have several loops to find the site desired. 

https://github.com/LunarWatcher/NN-chatbot/blob/master/Commands.py
Lines 28 - 32, 38 - 42, etc.

What I think would help is that since the `sites` object is an array, we could create an index object. What would be done is making a new line after line 20 that reads: `siteIndexs = {}`

A new line would be appended after line 31 that reads: `siteIndexs[site.name] = sites.indexOf(site)`

That enables us to do the following:

instead of: `for site in sites: #some verification method`
we would use:
`sites[siteIndexs[site.name]]`

**Comment by LunarWatcher** [comment]
Dicts are better. I'll look into it

**Comment by TheOneWhoMade** [comment]
Are dicts similar to an index array? Or the python equivalent?

**Comment by TheOneWhoMade** [comment]
Please mark this with "enhancement", "Priority: low", & "performance"

**Comment by TheOneWhoMade** [comment]
:SMILE

**Comment by TheOneWhoMade** [comment]
Take a look at this: http://gameprogrammingpatterns.com/data-locality.html#when-to-use-it

It's about game design patterns, but still relevant, as you are using event listeners.

**Comment by TheOneWhoMade** [comment]
Oh wow you went right up and changed it into a literal. (Is that what a dict is?)
