### ISSUE TITLE
Enable disabling sites

### ISSUE THREAD

**Issue by LunarWatcher** [LunarWatcher/NN-chatbot#2]
Add booleans in config.py to disable entire output sites.

I.e.:

    useDiscord = True

disabling it disables booting the site and adding it to the site list (for privileges).

**Comment by TheOneWhoMade** [comment]
Wait. In the config, would it be equivalent to a disable to leave an empty room array?
```
homes = {
    "stackoverflow.com": [1],
    "stackexchange.com": [1],
    "meta.stackexchange.com": []  # <=== like that
}
```

**Comment by LunarWatcher** [comment]
no, atm that would just not spawn it into rooms. It'd still log in. Working on a system now
