### ISSUE TITLE
Optimize boot

### ISSUE THREAD

**Issue by LunarWatcher** [LunarWatcher/NN-chatbot#23]
*Only applies to chatting*

Launch the bot and net async, so the bot can get online quickly independently of the network.

**Comment by TheOneWhoMade** [comment]
Use promises.

**Comment by TheOneWhoMade** [comment]
https://pypi.python.org/pypi/promise

**Comment by TheOneWhoMade** [comment]
You need to submit this as an issue here: https://github.com/Manishearth/ChatExchange/
Tell them that you are making a UI and that you would like them to have it be made to use async so it can boot faster. Often it is not actually your project but the dependencies of your project.

**Comment by LunarWatcher** [comment]
No... ChatExchange is the chat binding and has nothing to do with the bot itself.

**Comment by TheOneWhoMade** [comment]
It has to do with the method of logging the bot into the account.

**Comment by TheOneWhoMade** [comment]
LunarWatcher are you going to look at my pull request?

**Comment by TheOneWhoMade** [comment]
What the heck? You just screwed up my patch in your update.

**Comment by TheOneWhoMade** [comment]
Actually, its not that bad. Just look at the changes I made in `TheOneWhoMade patch-1`. Ignore the stuff at the top. Only look at the bottom of the `bot.py` and the config.
