### ISSUE TITLE
Summon and unsummon is broken

### ISSUE THREAD

**Issue by LunarWatcher** [LunarWatcher/NN-chatbot#25]
Idk why, doesn't work though

**Comment by TheOneWhoMade** [comment]
Might have something to do with those changes you removed.

**Comment by LunarWatcher** [comment]
Which changes?

**Comment by TheOneWhoMade** [comment]
The conversion of the tuple to the `if`. You may want to wrap that if statement in something.

**Comment by TheOneWhoMade** [comment]
Also, Images are helpfull. I don't care what they say on SO

**Comment by TheOneWhoMade** [comment]
Whoa dont go making those changes yet. Give me an image.

**Comment by TheOneWhoMade** [comment]
The only thing I can think that occured is a logic error. Somewhere, you went wrong,
