### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by LunarWatcher** [LunarWatcher/NN-chatbot#3]

**Comment by LunarWatcher** [comment]
Use recommended editions (meaning the requirements.txt file contains tensorflow-gpu)

    tensorflow-gpu
    discord.py
    numpy
    tensorlayer
    sklearn
    asyncio
    tensorboard

Versions should be added too, this is just an initial draft

**Comment by TheOneWhoMade** [comment]
I have a list of the most current versions.

**Comment by TheOneWhoMade** [comment]
```
tensorflow-gpu ???
discord.py ???
numpy 1.14.1
tensorlayer 1.8.0
sklearn 0.0  (Yeh thats a bit weird.)
asyncio 3.4.3
tensorboard 1.6.0
```

**Comment by TheOneWhoMade** [comment]
BTW you also forgot these dependecies:

python3-skimage,   nltk

**Comment by TheOneWhoMade** [comment]
Please change the `pip` on the README to `pip3` . pip wont work.

**Comment by LunarWatcher** [comment]
I just noticed nltk, skimage isn't used by the project itself so there's a different dependency that uses it. See the [note](https://github.com/LunarWatcher/NN-chatbot/blob/master/README.md#please-note) in README. 

As for changing to pip3 no. Which to use [depends on your python versions installed](https://stackoverflow.com/a/40832702/6296561)
