### ISSUE TITLE
CLI arguments

### ISSUE THREAD

**Issue by LunarWatcher** [LunarWatcher/NN-chatbot#31]
Save time - add CLI arguments to allow direct boot without prompting the user.

Necessary stuff:

* Parsing
* Set variables if the CLI argument for the relevant var isn't found
* Without getting in the way of the force training system

Relevant code:

Inside `if __name__ == "__main__"` in bot.py

**Comment by TheOneWhoMade** [comment]
Much better. But you should probably tell people what CLI stands for.

**Comment by TheOneWhoMade** [comment]
And that is not your first issue.

**Comment by TheOneWhoMade** [comment]
Is there a reason you can't just remove the print statements?

**Comment by TheOneWhoMade** [comment]
I'll work on it...

**Comment by TheOneWhoMade** [comment]
Ack!

**Comment by TheOneWhoMade** [comment]
Please look at #32

**Comment by LunarWatcher** [comment]
Clarification: This means running the script as:

    bot.py --training false --mode 0

would automatically fill in the values. But:

    bot.py --training false

still requests mode. It's to save time on boot.

**Comment by TheOneWhoMade** [comment]
so you want it to default mode to a certain value?
