### ISSUE TITLE
Contributing to the Wiki

### ISSUE THREAD

**Issue by Whispres** [LunarWatcher/NN-chatbot#52]
Given GitHub doesn't support pull requests for the wiki repository, contributors need a workaround to submit and collaborate on documentation.

I found a few possible suggestions on the internet:
1. [Including a github wiki in a repository as a submodule](https://brendancleary.com/2013/03/08/including-a-github-wiki-in-a-repository-as-a-submodule/)
2. [Enabling pull requests on github wikis setup](http://www.growingwiththeweb.com/2016/07/enabling-pull-requests-on-github-wikis.html)
3. Contributors clone the wiki; make changes to their version of the wiki repo; submit a link to their repo as an Issue; and request for it to be added to the main wiki.

**Comment by LunarWatcher** [comment]
Should be [status-complete] now. Can you verify? Try editing the wiki

**Comment by Whispres** [comment]
I was able to directly edit the wiki and add my document, but there are no collaborative tools for handling updates before changes are implemented. It would be easier for you to review and screen changes to the documentation if there was another system in place that mirrored a pull request.

**Comment by LunarWatcher** [comment]
Sorry 'bout the late reply. Working on setting up a wiki repo with sync, having some problems with adding the encrypted key. Should be ready soon, I'll close the issue with a link to it when I am finished

**Comment by LunarWatcher** [comment]
Done. Wiki changes can now be submitted [here](https://github.com/LunarWatcher/NN-chatbot-wiki/)
