### ISSUE TITLE
API cleanup

### ISSUE THREAD

**Issue by LunarWatcher** [LunarWatcher/NN-chatbot#64]
Most of the API is a mess. It needs to be refactored, and specifically the Java module.

The neural net could use some improvements too, specifically on memory use. It might need to be re-written from scratch.

**Comment by aredshaw** [comment]
Where do I find the current API info? Are some docs written already? I see there is nothing in the Wiki.

**Comment by LunarWatcher** [comment]
There is none. Javadoc/kdoc is also essentially non-existent. Issue 47 exists for a reason.

The cleanup issue mainly lies on making the code less messy, which among others includes moving all the code into one directory, removing redundant calls, moving duplicated calls into methods, and generally making it easier to extend. 

And also to add site-specific features such as editing and timed tasks without requiring too much code change
