### ISSUE TITLE
Summon and unsummon commands (SE)

### ISSUE THREAD

**Issue by LunarWatcher** [LunarWatcher/NN-chatbot#8]

**Comment by TheOneWhoMade** [comment]
Hmm. Could this be done by an `if(rooms[roomid].is_using):` statement?

**Comment by TheOneWhoMade** [comment]
I'm thinking the bot doesn't actually have to leave the room. Just ignore input from that room.

**Comment by TheOneWhoMade** [comment]
So that edit enables it to stop listening to a room?

**Comment by TheOneWhoMade** [comment]
I may not be able to install it yet, but I can still contribute.

**Comment by TheOneWhoMade** [comment]
Question: https://github.com/LunarWatcher/NN-chatbot/edit/master/Commands.py
Lines 38 - 40
What it the format of the `sites` object? Array?

**Comment by LunarWatcher** [comment]
@TheOneWhoMade see line 20, the type hint gives it away

**Comment by TheOneWhoMade** [comment]
Is it possible to make it into a literal from an array?

**Comment by TheOneWhoMade** [comment]
Please close this. If it is implemented now, it is no longer needed.

**Comment by LunarWatcher** [comment]
If you read the message in my commit which is referenced earlier, you'll see why it isn't closed
